### ISSUE TITLE
尝试使用了一下，发现用不了，插件无法生效

### ISSUE THREAD

**Issue by allworldg** [CodeZhangBorui/Jyeoo-Print-Processer#1]

**Comment by allworldg** [comment]
不好意思，原来脚本匹配的是http而不是https

**Comment by CodeZhangBorui** [comment]
:)

**Comment by CodeZhangBorui** [comment]
:)

**Comment by CodeZhangBorui** [comment]
添加https到脚本匹配

**Comment by CodeZhangBorui** [comment]
期末考试完再修

**Comment by CodeZhangBorui** [comment]
已修复，添加 https:// 匹配，[Install this User Script on Greasy Fork](https://greasyfork.org/zh-CN/scripts/446654-%E8%8F%81%E4%BC%98%E6%89%93%E5%8D%B0%E5%A4%84%E7%90%86%E7%A8%8B%E5%BA%8F)
